version: '2'
services:

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  postgres-data:
  pgadmin-data:

##
##  redis:
##    image: redis:alpine
##    ports:
##      - "6379:6379"
##
